version: "3.9"
services:
  comedic-node:
    build:
      context: ./MediColGes_Backend
      dockerfile: Dockerfile
    image: comedicimg
    container_name: comedic
    ports:
      - "5000:5000"
    restart: unless-stopped
